name: Test Package

on:
  push:
    branches:
      - enh/#13/pytest-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree CLI
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure before build
        run: tree

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Make sure this is compatible with your code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build setuptools

      - name: Build the package
        run: python -m build

      - name: Show directory structure after build
        run: tree

      - name: Verify that the build artifacts exist
        run: ls -l dist/  # Ensures that the package was actually built

      - name: Upload built artifacts
        if: success()  # Upload only if the build was successful
        uses: actions/upload-artifact@v4
        with:
          name: my_package
          path: dist/

  deploy:
    needs: build  # This ensures the build job completes successfully before starting the deploy job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # Ensures all steps use a login shell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniforge (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          miniforge-variant: Mambaforge
          use-mamba: true
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: mle-dev  # Automatically activates environment

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: my_package
          path: dist/

      - name: Install the package
        run: pip install dist/*.whl

      - name: Run the script from installed package
        run: python -m my_package.nonstandardcode

      - name: Run tests using pytest
        run: pytest tests/test_installation.py